version: '3'

services:

  nginx:
    container_name: lemp_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html

      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier

  php:
    container_name: lemp_php
    build: php/
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - back-tier
      
  db:
    container_name: lemp_mariadb
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=devops101
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101
    networks:
      - back-tier
    
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
    - '8080:80'
    networks:
      - back-tier
    links:
        - mysql:mysql
    environment:
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101
      - PMA_HOST=db

#        MYSQL_USERNAME: root
#        MYSQL_ROOT_PASSWORD: hakase-labs123
#        PMA_HOST: mysql    

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}

#networks:
#  default:
#    external:
#      name:
#        web_network